---
-   name: restart nginx
    service:
        name: nginx
        state: restarted
        enabled: yes

-   name: restart docker
    service:
        name: docker
        state: restarted