# Python CircleCI 2.1 configuration file
version: 2.1
orbs: 
    snyk: snyk/snyk@0.0.8

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: moody94/microblog
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest -f docker/Dockerfile_prod .
      - snyk/scan:
        docker-image-name: $IMAGE_NAME:latest
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt update
            python3 -m venv venv
            . venv/bin/activate
            pip install py pylint pytest coverage
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

  deploy-azure:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/microblog 
    steps:
      - checkout
      - run:
          name: Install deployment dependencies
          command: |
            sudo apt update
            sudo apt upgrade
            python3 -m venv venv
            . venv/bin/activate
            make install-deploy
      - run:
          name: Execute appServer playbook
          command: |
            . venv/bin/activate
            cd ansible
            ansible-playbook gather_vm_instances.yml appServer.yml

  snyk:
      docker:
          - image: circleci/python:3.5
      working_directory: ~/repo
      steps:
          - checkout
          - run:
              name: install dependencies
              command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  make install
          - run: echo "source ~/repo/venv/bin/activate" >> $BASH_ENV # här gör vi så att så att CircleCi automatisk laddar venv och då kollar Snyk vad vi har installerat i den.
          - snyk/scan
workflows:
  version: 2
  build-master:
    jobs:
      - snyk:
          filters:
            branches:
              only: master
      - test:
          requires:
            - snyk
          filters:
            branches:
              only: master
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-azure:
          requires:
            - publish-latest
          filters:
            branches:
              only: master
  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-tag:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

