# image name is pyhhon and tag is 3.8_alpine
FROM python:3.8-alpine

WORKDIR /home/microblog


COPY requirements requirements
COPY requirements.txt microblog.py boot_test.sh ./

RUN python -m venv .venv

# hadolint ignore=DL3013,DL3018
RUN apk --no-cache add --virtual build-dependencies libffi-dev openssl-dev py-pip build-base \
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && pip install -U setuptools \
  && pip install -U pylint \
  && apk del build-dependencies

# hadolint ignore=DL3013,DL3018
RUN apk add --no-cache bash  make cmake

RUN .venv/bin/pip3 install -r requirements.txt \
&& .venv/bin/pip3 install -r requirements/test.txt \
&& .venv/bin/pip3 install py pytest coverage pylint
RUN chmod +x boot_test.sh



# comands that should run when the contianer start
ENTRYPOINT ["./boot_test.sh"]