---
-   name: Add appServer
    hosts: appServer
    vars: 
        ansible_python_interpreter: /usr/bin/python3
    remote_user: deploy
    become: yes
    become_method: sudo
    roles:
        - appServer
