---
-   name: Add database
    hosts: database
    vars: 
        ansible_python_interpreter: /usr/bin/python3
    remote_user: deploy
    become: yes
    become_method: sudo
    roles:
        - database
