---
-   name: make monitor
    hosts: monitoring
    remote_user: deploy
    become: yes
    become_method: sudo
    vars: 
        ansible_python_interpreter: /usr/bin/python3
    roles: 
        - node-exporter
        - prometheus
        - grafana